"""
Django settings for nl project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(%_mx12o(as5=s2j&=9*d^&_1+**ocrl*mwmj!vz#+$fiyzd57'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# DEBUG = True

ADMINS = [('Administrador', 'suporteatena@see.ac.gov')]

# ALLOWED_HOSTS = ['177.203.207.29', '172.22.0.135', 'atena.see.ac.gov.br', 'www.atena.see.ac.gov.br'] #Produção
# ALLOWED_HOSTS = ['172.22.0.42', 'devatena.see.ac.gov.br', 'www.devatena.see.ac.gov.br'] #Homologação
ALLOWED_HOSTS = ['localhost'] #Desenvolvimento


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aplicacoes.usuario',
    'aplicacoes.atena',
    'aplicacoes.core',
    'aplicacoes.administracao',
    'aplicacoes.dinem',
    'aplicacoes.terceirizacao',
    'aplicacoes.lotacao',
    'aplicacoes.tecnologia',
    'aplicacoes.fundiaria',
    'aplicacoes.coex',
    'aplicacoes.dashboard',
    'aplicacoes.api',
    'aplicacoes.lotus',
    'aplicacoes.contas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #Produção/Homologação
]

ROOT_URLCONF = 'nl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'secretaria',
        'USER': 'see',
        'PASSWORD': 'dtmisee@',
        'HOST': 'mysql',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static') #Produção/Homologação
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Deslogando usuário do sistema
# SESSION_COOKIE_AGE = 900
# SESSION_SAVE_EVERY_REQUEST = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'suporteatena@see.ac.gov.br'
EMAIL_HOST_PASSWORD = 'jqomjljrxcdrenrk'
EMAIL_PORT = 587

# # # PRODUCAO
# LOGGING = {
#     'version': 1,
#     'loggers': {
#         'django': {
#             'handlers':['mail_admins'],
#             'level': 'INFO'
#         }
#     },

#     'handlers': {
#         # 'file': {
#         #     'level': 'INFO',
#         #     'class': 'logging.FileHandler',
#         #     'filename': './logs/debug.log',
#         #     'formatter': 'simple',
#         # },
#         'mail_admins': {
#             'level': 'WARNING',
#             'class': 'django.utils.log.AdminEmailHandler',
#             'include_html': True,
#             # 'reporter_class': 'django.views.debug.ExceptionReporter',
#         },
#     },
# }