# Generated by Django 4.1.7 on 2023-04-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado')], max_length=10)),
                ('atualizar_simaed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'aux_estado',
            },
        ),
        migrations.CreateModel(
            name='Importacao_simaed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('arquivo', models.FileField(upload_to='')),
                ('enturmacoes', models.IntegerField(default=0)),
                ('novas_enturmacoes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atena.estado')),
            ],
            options={
                'db_table': 'aux_cidade',
            },
        ),
        migrations.CreateModel(
            name='Aux_simaed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(blank=True, max_length=200, null=True)),
                ('escola', models.CharField(blank=True, max_length=200, null=True)),
                ('inep_escola', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_aluno', models.CharField(blank=True, max_length=200, null=True)),
                ('inep_aluno', models.CharField(blank=True, max_length=200, null=True)),
                ('nascimento', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo', models.CharField(blank=True, max_length=200, null=True)),
                ('cor', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('transporte', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_social', models.CharField(blank=True, max_length=200, null=True)),
                ('possui_deficiencia', models.CharField(blank=True, max_length=200, null=True)),
                ('deficiencia', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('celular', models.CharField(blank=True, max_length=200, null=True)),
                ('email_aluno', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf_aluno', models.CharField(blank=True, max_length=200, null=True)),
                ('bolsa_familia', models.CharField(blank=True, max_length=200, null=True)),
                ('cns', models.CharField(blank=True, max_length=200, null=True)),
                ('ra', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel', models.CharField(blank=True, max_length=200, null=True)),
                ('etapa', models.CharField(blank=True, max_length=200, null=True)),
                ('turno', models.CharField(blank=True, max_length=200, null=True)),
                ('turma', models.CharField(blank=True, max_length=200, null=True)),
                ('periodo_letivo', models.CharField(blank=True, max_length=200, null=True)),
                ('data_matricula', models.CharField(blank=True, max_length=200, null=True)),
                ('situacao_matricula', models.CharField(blank=True, max_length=200, null=True)),
                ('ano_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('exclusivo_aee', models.CharField(blank=True, max_length=200, null=True)),
                ('importacao_simaed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atena.importacao_simaed')),
            ],
        ),
    ]
